### ISSUE TITLE
jquery-cropper in modal window

### ISSUE THREAD

**Issue by Artgit** [fengyuanchen/jquery-cropper#3]
Hello, thanks for this awesome crop component! 

I have a question - do you have an example of how to use it in the modal window instead of placing the component directly into the page?

Thanks!

**Comment by AliMahmoud7** [comment]
Hi @Artgit!

You can check this example [cropper-in-modal](https://github.com/fengyuanchen/cropperjs/blob/master/examples/cropper-in-modal.html) or this [upload-cropped-image-to-server](https://github.com/fengyuanchen/cropperjs/blob/master/examples/upload-cropped-image-to-server.html) for the cropperjs.
You can use cropperjs instead of jquery-cropper and It'll work perfectly in the modals, Also you can use jquery-cropper but I prefer cropperjs.

Hope this help you.


Best,
Ali Mahmoud

**Comment by fengyuanchen** [comment]
The `examples` folder had been moved into the `docs` folder:

The right URLs:
- https://github.com/fengyuanchen/cropperjs/blob/master/docs/examples/cropper-in-modal.html
- https://github.com/fengyuanchen/cropperjs/blob/master/docs/examples/upload-cropped-image-to-server.html
